//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tech4mUI.Tech4mService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Tech4mService.ITech4mService")]
    public interface ITech4mService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateVideo", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateVideoResponse")]
        bool SaveUpdateVideo(int insertUpdateType, tech4mEntity.Video video);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateVideo", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateVideoResponse")]
        System.Threading.Tasks.Task<bool> SaveUpdateVideoAsync(int insertUpdateType, tech4mEntity.Video video);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteVideo", ReplyAction="http://tempuri.org/ITech4mService/DeleteVideoResponse")]
        bool DeleteVideo(int VideoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteVideo", ReplyAction="http://tempuri.org/ITech4mService/DeleteVideoResponse")]
        System.Threading.Tasks.Task<bool> DeleteVideoAsync(int VideoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetVideoList", ReplyAction="http://tempuri.org/ITech4mService/GetVideoListResponse")]
        tech4mEntity.Video[] GetVideoList(int videoId, int videoSubCategoryId, int videoCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetVideoList", ReplyAction="http://tempuri.org/ITech4mService/GetVideoListResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Video[]> GetVideoListAsync(int videoId, int videoSubCategoryId, int videoCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetVideo", ReplyAction="http://tempuri.org/ITech4mService/GetVideoResponse")]
        tech4mEntity.VideoViewModel[] GetVideo(int videoId, int videoSubCategoryId, int videoCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetVideo", ReplyAction="http://tempuri.org/ITech4mService/GetVideoResponse")]
        System.Threading.Tasks.Task<tech4mEntity.VideoViewModel[]> GetVideoAsync(int videoId, int videoSubCategoryId, int videoCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateBook", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateBookResponse")]
        bool SaveUpdateBook(int insertUpdateType, tech4mEntity.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateBook", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateBookResponse")]
        System.Threading.Tasks.Task<bool> SaveUpdateBookAsync(int insertUpdateType, tech4mEntity.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteBook", ReplyAction="http://tempuri.org/ITech4mService/DeleteBookResponse")]
        bool DeleteBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteBook", ReplyAction="http://tempuri.org/ITech4mService/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetBookList", ReplyAction="http://tempuri.org/ITech4mService/GetBookListResponse")]
        tech4mEntity.Book[] GetBookList(int bookId, int bookSubCategoryId, int bookCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetBookList", ReplyAction="http://tempuri.org/ITech4mService/GetBookListResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Book[]> GetBookListAsync(int bookId, int bookSubCategoryId, int bookCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SearchBookByISBN", ReplyAction="http://tempuri.org/ITech4mService/SearchBookByISBNResponse")]
        tech4mEntity.BookSearchViewModel[] SearchBookByISBN(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SearchBookByISBN", ReplyAction="http://tempuri.org/ITech4mService/SearchBookByISBNResponse")]
        System.Threading.Tasks.Task<tech4mEntity.BookSearchViewModel[]> SearchBookByISBNAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddCategory", ReplyAction="http://tempuri.org/ITech4mService/AddCategoryResponse")]
        int AddCategory(tech4mEntity.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddCategory", ReplyAction="http://tempuri.org/ITech4mService/AddCategoryResponse")]
        System.Threading.Tasks.Task<int> AddCategoryAsync(tech4mEntity.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateCategory", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateCategoryResponse")]
        bool SaveUpdateCategory(int insertUpdateType, tech4mEntity.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateCategory", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateCategoryResponse")]
        System.Threading.Tasks.Task<bool> SaveUpdateCategoryAsync(int insertUpdateType, tech4mEntity.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteCategory", ReplyAction="http://tempuri.org/ITech4mService/DeleteCategoryResponse")]
        bool DeleteCategory(int SubCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteCategory", ReplyAction="http://tempuri.org/ITech4mService/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int SubCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetCategoryList", ReplyAction="http://tempuri.org/ITech4mService/GetCategoryListResponse")]
        tech4mEntity.Category[] GetCategoryList(int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetCategoryList", ReplyAction="http://tempuri.org/ITech4mService/GetCategoryListResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Category[]> GetCategoryListAsync(int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalCategories", ReplyAction="http://tempuri.org/ITech4mService/TotalCategoriesResponse")]
        int TotalCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalCategories", ReplyAction="http://tempuri.org/ITech4mService/TotalCategoriesResponse")]
        System.Threading.Tasks.Task<int> TotalCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Category", ReplyAction="http://tempuri.org/ITech4mService/CategoryResponse")]
        tech4mEntity.Category Category(string categorySlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Category", ReplyAction="http://tempuri.org/ITech4mService/CategoryResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Category> CategoryAsync(string categorySlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditCategory", ReplyAction="http://tempuri.org/ITech4mService/EditCategoryResponse")]
        void EditCategory(tech4mEntity.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditCategory", ReplyAction="http://tempuri.org/ITech4mService/EditCategoryResponse")]
        System.Threading.Tasks.Task EditCategoryAsync(tech4mEntity.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Categories", ReplyAction="http://tempuri.org/ITech4mService/CategoriesResponse")]
        tech4mEntity.Category[] Categories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Categories", ReplyAction="http://tempuri.org/ITech4mService/CategoriesResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Category[]> CategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddSubCategory", ReplyAction="http://tempuri.org/ITech4mService/AddSubCategoryResponse")]
        int AddSubCategory(tech4mEntity.SubCategory subCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddSubCategory", ReplyAction="http://tempuri.org/ITech4mService/AddSubCategoryResponse")]
        System.Threading.Tasks.Task<int> AddSubCategoryAsync(tech4mEntity.SubCategory subCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateSubCategory", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateSubCategoryResponse")]
        bool SaveUpdateSubCategory(int insertUpdateType, tech4mEntity.SubCategory subCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateSubCategory", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateSubCategoryResponse")]
        System.Threading.Tasks.Task<bool> SaveUpdateSubCategoryAsync(int insertUpdateType, tech4mEntity.SubCategory subCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteSubCategory", ReplyAction="http://tempuri.org/ITech4mService/DeleteSubCategoryResponse")]
        bool DeleteSubCategory(int SubCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteSubCategory", ReplyAction="http://tempuri.org/ITech4mService/DeleteSubCategoryResponse")]
        System.Threading.Tasks.Task<bool> DeleteSubCategoryAsync(int SubCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetSubCategoryListByCategoryId", ReplyAction="http://tempuri.org/ITech4mService/GetSubCategoryListByCategoryIdResponse")]
        tech4mEntity.SubCategory[] GetSubCategoryListByCategoryId(int categoryId, int subCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetSubCategoryListByCategoryId", ReplyAction="http://tempuri.org/ITech4mService/GetSubCategoryListByCategoryIdResponse")]
        System.Threading.Tasks.Task<tech4mEntity.SubCategory[]> GetSubCategoryListByCategoryIdAsync(int categoryId, int subCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalSubCategories", ReplyAction="http://tempuri.org/ITech4mService/TotalSubCategoriesResponse")]
        int TotalSubCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalSubCategories", ReplyAction="http://tempuri.org/ITech4mService/TotalSubCategoriesResponse")]
        System.Threading.Tasks.Task<int> TotalSubCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditSubCategory", ReplyAction="http://tempuri.org/ITech4mService/EditSubCategoryResponse")]
        void EditSubCategory(tech4mEntity.SubCategory subCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditSubCategory", ReplyAction="http://tempuri.org/ITech4mService/EditSubCategoryResponse")]
        System.Threading.Tasks.Task EditSubCategoryAsync(tech4mEntity.SubCategory subCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SubCategories", ReplyAction="http://tempuri.org/ITech4mService/SubCategoriesResponse")]
        tech4mEntity.SubCategory[] SubCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SubCategories", ReplyAction="http://tempuri.org/ITech4mService/SubCategoriesResponse")]
        System.Threading.Tasks.Task<tech4mEntity.SubCategory[]> SubCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestion", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestionResponse")]
        bool SaveUpdateInterviewQuestion(int insertUpdateType, tech4mEntity.InterviewQuestion interviewQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestion", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestionResponse")]
        System.Threading.Tasks.Task<bool> SaveUpdateInterviewQuestionAsync(int insertUpdateType, tech4mEntity.InterviewQuestion interviewQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteInterviewQuestion", ReplyAction="http://tempuri.org/ITech4mService/DeleteInterviewQuestionResponse")]
        bool DeleteInterviewQuestion(int InterviewQuestionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteInterviewQuestion", ReplyAction="http://tempuri.org/ITech4mService/DeleteInterviewQuestionResponse")]
        System.Threading.Tasks.Task<bool> DeleteInterviewQuestionAsync(int InterviewQuestionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionList", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionListResponse")]
        tech4mEntity.InterviewQuestion[] GetInterviewQuestionList(int InterviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionList", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionListResponse")]
        System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion[]> GetInterviewQuestionListAsync(int InterviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionById", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionByIdResponse")]
        tech4mEntity.InterviewQuestion GetInterviewQuestionById(int interviewQuestionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionById", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionByIdResponse")]
        System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion> GetInterviewQuestionByIdAsync(int interviewQuestionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionListByCategory", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionListByCategoryResponse")]
        tech4mEntity.InterviewQuestion[] GetInterviewQuestionListByCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionListByCategory", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionListByCategoryResponse")]
        System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion[]> GetInterviewQuestionListByCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionListByBySubCategory", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionListByBySubCategoryResponse" +
            "")]
        tech4mEntity.InterviewQuestion[] GetInterviewQuestionListByBySubCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionListByBySubCategory", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionListByBySubCategoryResponse" +
            "")]
        System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion[]> GetInterviewQuestionListByBySubCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddInterviewQuestionToPlayList", ReplyAction="http://tempuri.org/ITech4mService/AddInterviewQuestionToPlayListResponse")]
        bool AddInterviewQuestionToPlayList(int playList, tech4mEntity.InterviewQuestion interviewQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddInterviewQuestionToPlayList", ReplyAction="http://tempuri.org/ITech4mService/AddInterviewQuestionToPlayListResponse")]
        System.Threading.Tasks.Task<bool> AddInterviewQuestionToPlayListAsync(int playList, tech4mEntity.InterviewQuestion interviewQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestionAnswer", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestionAnswerResponse")]
        bool SaveUpdateInterviewQuestionAnswer(int insertUpdateType, tech4mEntity.InterviewQuestionAnswer interviewQuestionAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestionAnswer", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateInterviewQuestionAnswerResponse")]
        System.Threading.Tasks.Task<bool> SaveUpdateInterviewQuestionAnswerAsync(int insertUpdateType, tech4mEntity.InterviewQuestionAnswer interviewQuestionAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionAnswer", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionAnswerResponse")]
        tech4mEntity.InterviewQuestionAnswerViewModel GetInterviewQuestionAnswer(int interviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetInterviewQuestionAnswer", ReplyAction="http://tempuri.org/ITech4mService/GetInterviewQuestionAnswerResponse")]
        System.Threading.Tasks.Task<tech4mEntity.InterviewQuestionAnswerViewModel> GetInterviewQuestionAnswerAsync(int interviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateArticle", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateArticleResponse")]
        bool SaveUpdateArticle(int insertUpdateType, tech4mEntity.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/SaveUpdateArticle", ReplyAction="http://tempuri.org/ITech4mService/SaveUpdateArticleResponse")]
        System.Threading.Tasks.Task<bool> SaveUpdateArticleAsync(int insertUpdateType, tech4mEntity.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteArticle", ReplyAction="http://tempuri.org/ITech4mService/DeleteArticleResponse")]
        bool DeleteArticle(int articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteArticle", ReplyAction="http://tempuri.org/ITech4mService/DeleteArticleResponse")]
        System.Threading.Tasks.Task<bool> DeleteArticleAsync(int articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetArticleList", ReplyAction="http://tempuri.org/ITech4mService/GetArticleListResponse")]
        tech4mEntity.Article[] GetArticleList(int articleId, int articSubCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/GetArticleList", ReplyAction="http://tempuri.org/ITech4mService/GetArticleListResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Article[]> GetArticleListAsync(int articleId, int articSubCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostWithPaging", ReplyAction="http://tempuri.org/ITech4mService/PostWithPagingResponse")]
        tech4mEntity.Post[] PostWithPaging(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostWithPaging", ReplyAction="http://tempuri.org/ITech4mService/PostWithPagingResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Post[]> PostWithPagingAsync(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostsForTag", ReplyAction="http://tempuri.org/ITech4mService/PostsForTagResponse")]
        tech4mEntity.Post[] PostsForTag(string tagSlug, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostsForTag", ReplyAction="http://tempuri.org/ITech4mService/PostsForTagResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Post[]> PostsForTagAsync(string tagSlug, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostsForCategory", ReplyAction="http://tempuri.org/ITech4mService/PostsForCategoryResponse")]
        tech4mEntity.Post[] PostsForCategory(string categorySlug, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostsForCategory", ReplyAction="http://tempuri.org/ITech4mService/PostsForCategoryResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Post[]> PostsForCategoryAsync(string categorySlug, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostsForSearch", ReplyAction="http://tempuri.org/ITech4mService/PostsForSearchResponse")]
        tech4mEntity.Post[] PostsForSearch(string search, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostsForSearch", ReplyAction="http://tempuri.org/ITech4mService/PostsForSearchResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Post[]> PostsForSearchAsync(string search, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPosts", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsResponse")]
        int TotalPosts(bool checkIsPublished);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPosts", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsResponse")]
        System.Threading.Tasks.Task<int> TotalPostsAsync(bool checkIsPublished);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPostsForCategory", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsForCategoryResponse")]
        int TotalPostsForCategory(string categorySlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPostsForCategory", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsForCategoryResponse")]
        System.Threading.Tasks.Task<int> TotalPostsForCategoryAsync(string categorySlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPostsForTag", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsForTagResponse")]
        int TotalPostsForTag(string tagSlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPostsForTag", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsForTagResponse")]
        System.Threading.Tasks.Task<int> TotalPostsForTagAsync(string tagSlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPostsForSearch", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsForSearchResponse")]
        int TotalPostsForSearch(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalPostsForSearch", ReplyAction="http://tempuri.org/ITech4mService/TotalPostsForSearchResponse")]
        System.Threading.Tasks.Task<int> TotalPostsForSearchAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostListWithSort", ReplyAction="http://tempuri.org/ITech4mService/PostListWithSortResponse")]
        tech4mEntity.Post[] PostListWithSort(int pageNo, int pageSize, string sortColumn, bool sortByAscending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostListWithSort", ReplyAction="http://tempuri.org/ITech4mService/PostListWithSortResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Post[]> PostListWithSortAsync(int pageNo, int pageSize, string sortColumn, bool sortByAscending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostByMonthYear", ReplyAction="http://tempuri.org/ITech4mService/PostByMonthYearResponse")]
        tech4mEntity.Post PostByMonthYear(int year, int month, string titleSlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostByMonthYear", ReplyAction="http://tempuri.org/ITech4mService/PostByMonthYearResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Post> PostByMonthYearAsync(int year, int month, string titleSlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostByUniqueId", ReplyAction="http://tempuri.org/ITech4mService/PostByUniqueIdResponse")]
        tech4mEntity.Post PostByUniqueId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/PostByUniqueId", ReplyAction="http://tempuri.org/ITech4mService/PostByUniqueIdResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Post> PostByUniqueIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddPost", ReplyAction="http://tempuri.org/ITech4mService/AddPostResponse")]
        int AddPost(tech4mEntity.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddPost", ReplyAction="http://tempuri.org/ITech4mService/AddPostResponse")]
        System.Threading.Tasks.Task<int> AddPostAsync(tech4mEntity.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditPost", ReplyAction="http://tempuri.org/ITech4mService/EditPostResponse")]
        void EditPost(tech4mEntity.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditPost", ReplyAction="http://tempuri.org/ITech4mService/EditPostResponse")]
        System.Threading.Tasks.Task EditPostAsync(tech4mEntity.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeletePost", ReplyAction="http://tempuri.org/ITech4mService/DeletePostResponse")]
        void DeletePost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeletePost", ReplyAction="http://tempuri.org/ITech4mService/DeletePostResponse")]
        System.Threading.Tasks.Task DeletePostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Tags", ReplyAction="http://tempuri.org/ITech4mService/TagsResponse")]
        tech4mEntity.Tag[] Tags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Tags", ReplyAction="http://tempuri.org/ITech4mService/TagsResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Tag[]> TagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalTags", ReplyAction="http://tempuri.org/ITech4mService/TotalTagsResponse")]
        int TotalTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TotalTags", ReplyAction="http://tempuri.org/ITech4mService/TotalTagsResponse")]
        System.Threading.Tasks.Task<int> TotalTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Tag", ReplyAction="http://tempuri.org/ITech4mService/TagResponse")]
        tech4mEntity.Tag Tag(string tagSlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/Tag", ReplyAction="http://tempuri.org/ITech4mService/TagResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Tag> TagAsync(string tagSlug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TagByUniqueId", ReplyAction="http://tempuri.org/ITech4mService/TagByUniqueIdResponse")]
        tech4mEntity.Tag TagByUniqueId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/TagByUniqueId", ReplyAction="http://tempuri.org/ITech4mService/TagByUniqueIdResponse")]
        System.Threading.Tasks.Task<tech4mEntity.Tag> TagByUniqueIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddTag", ReplyAction="http://tempuri.org/ITech4mService/AddTagResponse")]
        int AddTag(tech4mEntity.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/AddTag", ReplyAction="http://tempuri.org/ITech4mService/AddTagResponse")]
        System.Threading.Tasks.Task<int> AddTagAsync(tech4mEntity.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditTag", ReplyAction="http://tempuri.org/ITech4mService/EditTagResponse")]
        void EditTag(tech4mEntity.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/EditTag", ReplyAction="http://tempuri.org/ITech4mService/EditTagResponse")]
        System.Threading.Tasks.Task EditTagAsync(tech4mEntity.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteTag", ReplyAction="http://tempuri.org/ITech4mService/DeleteTagResponse")]
        void DeleteTag(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITech4mService/DeleteTag", ReplyAction="http://tempuri.org/ITech4mService/DeleteTagResponse")]
        System.Threading.Tasks.Task DeleteTagAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITech4mServiceChannel : tech4mUI.Tech4mService.ITech4mService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Tech4mServiceClient : System.ServiceModel.ClientBase<tech4mUI.Tech4mService.ITech4mService>, tech4mUI.Tech4mService.ITech4mService {
        
        public Tech4mServiceClient() {
        }
        
        public Tech4mServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Tech4mServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Tech4mServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Tech4mServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveUpdateVideo(int insertUpdateType, tech4mEntity.Video video) {
            return base.Channel.SaveUpdateVideo(insertUpdateType, video);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUpdateVideoAsync(int insertUpdateType, tech4mEntity.Video video) {
            return base.Channel.SaveUpdateVideoAsync(insertUpdateType, video);
        }
        
        public bool DeleteVideo(int VideoId) {
            return base.Channel.DeleteVideo(VideoId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteVideoAsync(int VideoId) {
            return base.Channel.DeleteVideoAsync(VideoId);
        }
        
        public tech4mEntity.Video[] GetVideoList(int videoId, int videoSubCategoryId, int videoCategoryId) {
            return base.Channel.GetVideoList(videoId, videoSubCategoryId, videoCategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Video[]> GetVideoListAsync(int videoId, int videoSubCategoryId, int videoCategoryId) {
            return base.Channel.GetVideoListAsync(videoId, videoSubCategoryId, videoCategoryId);
        }
        
        public tech4mEntity.VideoViewModel[] GetVideo(int videoId, int videoSubCategoryId, int videoCategoryId) {
            return base.Channel.GetVideo(videoId, videoSubCategoryId, videoCategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.VideoViewModel[]> GetVideoAsync(int videoId, int videoSubCategoryId, int videoCategoryId) {
            return base.Channel.GetVideoAsync(videoId, videoSubCategoryId, videoCategoryId);
        }
        
        public bool SaveUpdateBook(int insertUpdateType, tech4mEntity.Book book) {
            return base.Channel.SaveUpdateBook(insertUpdateType, book);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUpdateBookAsync(int insertUpdateType, tech4mEntity.Book book) {
            return base.Channel.SaveUpdateBookAsync(insertUpdateType, book);
        }
        
        public bool DeleteBook(int bookId) {
            return base.Channel.DeleteBook(bookId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(int bookId) {
            return base.Channel.DeleteBookAsync(bookId);
        }
        
        public tech4mEntity.Book[] GetBookList(int bookId, int bookSubCategoryId, int bookCategoryId) {
            return base.Channel.GetBookList(bookId, bookSubCategoryId, bookCategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Book[]> GetBookListAsync(int bookId, int bookSubCategoryId, int bookCategoryId) {
            return base.Channel.GetBookListAsync(bookId, bookSubCategoryId, bookCategoryId);
        }
        
        public tech4mEntity.BookSearchViewModel[] SearchBookByISBN(string isbn) {
            return base.Channel.SearchBookByISBN(isbn);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.BookSearchViewModel[]> SearchBookByISBNAsync(string isbn) {
            return base.Channel.SearchBookByISBNAsync(isbn);
        }
        
        public int AddCategory(tech4mEntity.Category category) {
            return base.Channel.AddCategory(category);
        }
        
        public System.Threading.Tasks.Task<int> AddCategoryAsync(tech4mEntity.Category category) {
            return base.Channel.AddCategoryAsync(category);
        }
        
        public bool SaveUpdateCategory(int insertUpdateType, tech4mEntity.Category category) {
            return base.Channel.SaveUpdateCategory(insertUpdateType, category);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUpdateCategoryAsync(int insertUpdateType, tech4mEntity.Category category) {
            return base.Channel.SaveUpdateCategoryAsync(insertUpdateType, category);
        }
        
        public bool DeleteCategory(int SubCategoryId) {
            return base.Channel.DeleteCategory(SubCategoryId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int SubCategoryId) {
            return base.Channel.DeleteCategoryAsync(SubCategoryId);
        }
        
        public tech4mEntity.Category[] GetCategoryList(int CategoryId) {
            return base.Channel.GetCategoryList(CategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Category[]> GetCategoryListAsync(int CategoryId) {
            return base.Channel.GetCategoryListAsync(CategoryId);
        }
        
        public int TotalCategories() {
            return base.Channel.TotalCategories();
        }
        
        public System.Threading.Tasks.Task<int> TotalCategoriesAsync() {
            return base.Channel.TotalCategoriesAsync();
        }
        
        public tech4mEntity.Category Category(string categorySlug) {
            return base.Channel.Category(categorySlug);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Category> CategoryAsync(string categorySlug) {
            return base.Channel.CategoryAsync(categorySlug);
        }
        
        public void EditCategory(tech4mEntity.Category category) {
            base.Channel.EditCategory(category);
        }
        
        public System.Threading.Tasks.Task EditCategoryAsync(tech4mEntity.Category category) {
            return base.Channel.EditCategoryAsync(category);
        }
        
        public tech4mEntity.Category[] Categories() {
            return base.Channel.Categories();
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Category[]> CategoriesAsync() {
            return base.Channel.CategoriesAsync();
        }
        
        public int AddSubCategory(tech4mEntity.SubCategory subCategory) {
            return base.Channel.AddSubCategory(subCategory);
        }
        
        public System.Threading.Tasks.Task<int> AddSubCategoryAsync(tech4mEntity.SubCategory subCategory) {
            return base.Channel.AddSubCategoryAsync(subCategory);
        }
        
        public bool SaveUpdateSubCategory(int insertUpdateType, tech4mEntity.SubCategory subCategory) {
            return base.Channel.SaveUpdateSubCategory(insertUpdateType, subCategory);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUpdateSubCategoryAsync(int insertUpdateType, tech4mEntity.SubCategory subCategory) {
            return base.Channel.SaveUpdateSubCategoryAsync(insertUpdateType, subCategory);
        }
        
        public bool DeleteSubCategory(int SubCategoryId) {
            return base.Channel.DeleteSubCategory(SubCategoryId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSubCategoryAsync(int SubCategoryId) {
            return base.Channel.DeleteSubCategoryAsync(SubCategoryId);
        }
        
        public tech4mEntity.SubCategory[] GetSubCategoryListByCategoryId(int categoryId, int subCategoryId) {
            return base.Channel.GetSubCategoryListByCategoryId(categoryId, subCategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.SubCategory[]> GetSubCategoryListByCategoryIdAsync(int categoryId, int subCategoryId) {
            return base.Channel.GetSubCategoryListByCategoryIdAsync(categoryId, subCategoryId);
        }
        
        public int TotalSubCategories() {
            return base.Channel.TotalSubCategories();
        }
        
        public System.Threading.Tasks.Task<int> TotalSubCategoriesAsync() {
            return base.Channel.TotalSubCategoriesAsync();
        }
        
        public void EditSubCategory(tech4mEntity.SubCategory subCategory) {
            base.Channel.EditSubCategory(subCategory);
        }
        
        public System.Threading.Tasks.Task EditSubCategoryAsync(tech4mEntity.SubCategory subCategory) {
            return base.Channel.EditSubCategoryAsync(subCategory);
        }
        
        public tech4mEntity.SubCategory[] SubCategories() {
            return base.Channel.SubCategories();
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.SubCategory[]> SubCategoriesAsync() {
            return base.Channel.SubCategoriesAsync();
        }
        
        public bool SaveUpdateInterviewQuestion(int insertUpdateType, tech4mEntity.InterviewQuestion interviewQuestion) {
            return base.Channel.SaveUpdateInterviewQuestion(insertUpdateType, interviewQuestion);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUpdateInterviewQuestionAsync(int insertUpdateType, tech4mEntity.InterviewQuestion interviewQuestion) {
            return base.Channel.SaveUpdateInterviewQuestionAsync(insertUpdateType, interviewQuestion);
        }
        
        public bool DeleteInterviewQuestion(int InterviewQuestionId) {
            return base.Channel.DeleteInterviewQuestion(InterviewQuestionId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteInterviewQuestionAsync(int InterviewQuestionId) {
            return base.Channel.DeleteInterviewQuestionAsync(InterviewQuestionId);
        }
        
        public tech4mEntity.InterviewQuestion[] GetInterviewQuestionList(int InterviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId) {
            return base.Channel.GetInterviewQuestionList(InterviewQuestionId, interviewQuestionSubCategoryId, interviewQuestionCategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion[]> GetInterviewQuestionListAsync(int InterviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId) {
            return base.Channel.GetInterviewQuestionListAsync(InterviewQuestionId, interviewQuestionSubCategoryId, interviewQuestionCategoryId);
        }
        
        public tech4mEntity.InterviewQuestion GetInterviewQuestionById(int interviewQuestionId) {
            return base.Channel.GetInterviewQuestionById(interviewQuestionId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion> GetInterviewQuestionByIdAsync(int interviewQuestionId) {
            return base.Channel.GetInterviewQuestionByIdAsync(interviewQuestionId);
        }
        
        public tech4mEntity.InterviewQuestion[] GetInterviewQuestionListByCategory() {
            return base.Channel.GetInterviewQuestionListByCategory();
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion[]> GetInterviewQuestionListByCategoryAsync() {
            return base.Channel.GetInterviewQuestionListByCategoryAsync();
        }
        
        public tech4mEntity.InterviewQuestion[] GetInterviewQuestionListByBySubCategory() {
            return base.Channel.GetInterviewQuestionListByBySubCategory();
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.InterviewQuestion[]> GetInterviewQuestionListByBySubCategoryAsync() {
            return base.Channel.GetInterviewQuestionListByBySubCategoryAsync();
        }
        
        public bool AddInterviewQuestionToPlayList(int playList, tech4mEntity.InterviewQuestion interviewQuestion) {
            return base.Channel.AddInterviewQuestionToPlayList(playList, interviewQuestion);
        }
        
        public System.Threading.Tasks.Task<bool> AddInterviewQuestionToPlayListAsync(int playList, tech4mEntity.InterviewQuestion interviewQuestion) {
            return base.Channel.AddInterviewQuestionToPlayListAsync(playList, interviewQuestion);
        }
        
        public bool SaveUpdateInterviewQuestionAnswer(int insertUpdateType, tech4mEntity.InterviewQuestionAnswer interviewQuestionAnswer) {
            return base.Channel.SaveUpdateInterviewQuestionAnswer(insertUpdateType, interviewQuestionAnswer);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUpdateInterviewQuestionAnswerAsync(int insertUpdateType, tech4mEntity.InterviewQuestionAnswer interviewQuestionAnswer) {
            return base.Channel.SaveUpdateInterviewQuestionAnswerAsync(insertUpdateType, interviewQuestionAnswer);
        }
        
        public tech4mEntity.InterviewQuestionAnswerViewModel GetInterviewQuestionAnswer(int interviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId) {
            return base.Channel.GetInterviewQuestionAnswer(interviewQuestionId, interviewQuestionSubCategoryId, interviewQuestionCategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.InterviewQuestionAnswerViewModel> GetInterviewQuestionAnswerAsync(int interviewQuestionId, int interviewQuestionSubCategoryId, int interviewQuestionCategoryId) {
            return base.Channel.GetInterviewQuestionAnswerAsync(interviewQuestionId, interviewQuestionSubCategoryId, interviewQuestionCategoryId);
        }
        
        public bool SaveUpdateArticle(int insertUpdateType, tech4mEntity.Article article) {
            return base.Channel.SaveUpdateArticle(insertUpdateType, article);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUpdateArticleAsync(int insertUpdateType, tech4mEntity.Article article) {
            return base.Channel.SaveUpdateArticleAsync(insertUpdateType, article);
        }
        
        public bool DeleteArticle(int articleId) {
            return base.Channel.DeleteArticle(articleId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteArticleAsync(int articleId) {
            return base.Channel.DeleteArticleAsync(articleId);
        }
        
        public tech4mEntity.Article[] GetArticleList(int articleId, int articSubCategoryId) {
            return base.Channel.GetArticleList(articleId, articSubCategoryId);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Article[]> GetArticleListAsync(int articleId, int articSubCategoryId) {
            return base.Channel.GetArticleListAsync(articleId, articSubCategoryId);
        }
        
        public tech4mEntity.Post[] PostWithPaging(int pageNo, int pageSize) {
            return base.Channel.PostWithPaging(pageNo, pageSize);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Post[]> PostWithPagingAsync(int pageNo, int pageSize) {
            return base.Channel.PostWithPagingAsync(pageNo, pageSize);
        }
        
        public tech4mEntity.Post[] PostsForTag(string tagSlug, int pageNo, int pageSize) {
            return base.Channel.PostsForTag(tagSlug, pageNo, pageSize);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Post[]> PostsForTagAsync(string tagSlug, int pageNo, int pageSize) {
            return base.Channel.PostsForTagAsync(tagSlug, pageNo, pageSize);
        }
        
        public tech4mEntity.Post[] PostsForCategory(string categorySlug, int pageNo, int pageSize) {
            return base.Channel.PostsForCategory(categorySlug, pageNo, pageSize);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Post[]> PostsForCategoryAsync(string categorySlug, int pageNo, int pageSize) {
            return base.Channel.PostsForCategoryAsync(categorySlug, pageNo, pageSize);
        }
        
        public tech4mEntity.Post[] PostsForSearch(string search, int pageNo, int pageSize) {
            return base.Channel.PostsForSearch(search, pageNo, pageSize);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Post[]> PostsForSearchAsync(string search, int pageNo, int pageSize) {
            return base.Channel.PostsForSearchAsync(search, pageNo, pageSize);
        }
        
        public int TotalPosts(bool checkIsPublished) {
            return base.Channel.TotalPosts(checkIsPublished);
        }
        
        public System.Threading.Tasks.Task<int> TotalPostsAsync(bool checkIsPublished) {
            return base.Channel.TotalPostsAsync(checkIsPublished);
        }
        
        public int TotalPostsForCategory(string categorySlug) {
            return base.Channel.TotalPostsForCategory(categorySlug);
        }
        
        public System.Threading.Tasks.Task<int> TotalPostsForCategoryAsync(string categorySlug) {
            return base.Channel.TotalPostsForCategoryAsync(categorySlug);
        }
        
        public int TotalPostsForTag(string tagSlug) {
            return base.Channel.TotalPostsForTag(tagSlug);
        }
        
        public System.Threading.Tasks.Task<int> TotalPostsForTagAsync(string tagSlug) {
            return base.Channel.TotalPostsForTagAsync(tagSlug);
        }
        
        public int TotalPostsForSearch(string search) {
            return base.Channel.TotalPostsForSearch(search);
        }
        
        public System.Threading.Tasks.Task<int> TotalPostsForSearchAsync(string search) {
            return base.Channel.TotalPostsForSearchAsync(search);
        }
        
        public tech4mEntity.Post[] PostListWithSort(int pageNo, int pageSize, string sortColumn, bool sortByAscending) {
            return base.Channel.PostListWithSort(pageNo, pageSize, sortColumn, sortByAscending);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Post[]> PostListWithSortAsync(int pageNo, int pageSize, string sortColumn, bool sortByAscending) {
            return base.Channel.PostListWithSortAsync(pageNo, pageSize, sortColumn, sortByAscending);
        }
        
        public tech4mEntity.Post PostByMonthYear(int year, int month, string titleSlug) {
            return base.Channel.PostByMonthYear(year, month, titleSlug);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Post> PostByMonthYearAsync(int year, int month, string titleSlug) {
            return base.Channel.PostByMonthYearAsync(year, month, titleSlug);
        }
        
        public tech4mEntity.Post PostByUniqueId(int id) {
            return base.Channel.PostByUniqueId(id);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Post> PostByUniqueIdAsync(int id) {
            return base.Channel.PostByUniqueIdAsync(id);
        }
        
        public int AddPost(tech4mEntity.Post post) {
            return base.Channel.AddPost(post);
        }
        
        public System.Threading.Tasks.Task<int> AddPostAsync(tech4mEntity.Post post) {
            return base.Channel.AddPostAsync(post);
        }
        
        public void EditPost(tech4mEntity.Post post) {
            base.Channel.EditPost(post);
        }
        
        public System.Threading.Tasks.Task EditPostAsync(tech4mEntity.Post post) {
            return base.Channel.EditPostAsync(post);
        }
        
        public void DeletePost(int id) {
            base.Channel.DeletePost(id);
        }
        
        public System.Threading.Tasks.Task DeletePostAsync(int id) {
            return base.Channel.DeletePostAsync(id);
        }
        
        public tech4mEntity.Tag[] Tags() {
            return base.Channel.Tags();
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Tag[]> TagsAsync() {
            return base.Channel.TagsAsync();
        }
        
        public int TotalTags() {
            return base.Channel.TotalTags();
        }
        
        public System.Threading.Tasks.Task<int> TotalTagsAsync() {
            return base.Channel.TotalTagsAsync();
        }
        
        public tech4mEntity.Tag Tag(string tagSlug) {
            return base.Channel.Tag(tagSlug);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Tag> TagAsync(string tagSlug) {
            return base.Channel.TagAsync(tagSlug);
        }
        
        public tech4mEntity.Tag TagByUniqueId(int id) {
            return base.Channel.TagByUniqueId(id);
        }
        
        public System.Threading.Tasks.Task<tech4mEntity.Tag> TagByUniqueIdAsync(int id) {
            return base.Channel.TagByUniqueIdAsync(id);
        }
        
        public int AddTag(tech4mEntity.Tag tag) {
            return base.Channel.AddTag(tag);
        }
        
        public System.Threading.Tasks.Task<int> AddTagAsync(tech4mEntity.Tag tag) {
            return base.Channel.AddTagAsync(tag);
        }
        
        public void EditTag(tech4mEntity.Tag tag) {
            base.Channel.EditTag(tag);
        }
        
        public System.Threading.Tasks.Task EditTagAsync(tech4mEntity.Tag tag) {
            return base.Channel.EditTagAsync(tag);
        }
        
        public void DeleteTag(int id) {
            base.Channel.DeleteTag(id);
        }
        
        public System.Threading.Tasks.Task DeleteTagAsync(int id) {
            return base.Channel.DeleteTagAsync(id);
        }
    }
}
